version: "3.3"
services:
    zk1:
        image: akhil1980/zk
        restart: always
        container_name: zk1
        networks:
            - rts1
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
        volumes:
            - /home/akhil/fs/config/:/zookeeper/conf/
            - /home/akhil/fs/dataDir/zk1:/dataDir
            - /home/akhil/fs/logDir/zk1:/logDir/
    zk2:
        image: akhil1980/zk
        restart: always
        container_name: zk2
        networks:
            - rts1
        ports:
            - 2182:2181
            - 2889:2888
            - 3889:3888
        volumes:
            - /home/akhil/fs/config/:/zookeeper/conf/
            - /home/akhil/fs/dataDir/zk2:/dataDir
            - /home/akhil/fs/logDir/zk2:/logDir/
    zk3:
        image: akhil1980/zk
        restart: always
        container_name: zk3
        networks:
            - rts1
        ports:
            - 2183:2181
            - 2890:2888
            - 3890:3888
        volumes:
            - /home/akhil/fs/config/:/zookeeper/conf/
            - /home/akhil/fs/dataDir/zk3:/dataDir 
            - /home/akhil/fs/logDir/zk3:/logDir/
    k1:
       image: akhil1980/kafka
       container_name: k1
       networks:
           - rts1
       ports:
           - 9092:9092
       volumes:
           - /home/akhil/fs/kafka/k1:/config
           - /home/akhil/fs/kafka/k1/logDir:/logDir
    k2:
       image: akhil1980/kafka
       container_name: k2
       networks:
           - rts1
       ports:
           - 9093:9092
       volumes:
           - /home/akhil/fs/kafka/k2:/config
           - /home/akhil/fs/kafka/k2/logDir:/logDir
    k3:
       image: akhil1980/kafka
       container_name: k3
       networks:
           - rts1
       ports:
           - 9094:9092
       volumes:
           - /home/akhil/fs/kafka/k3:/config
           - /home/akhil/fs/kafka/k3/logDir:/logDir

networks:
    rts1:
         driver: bridge
         internal: true

