from akhil1980/alpinejdk:8
RUN wget "http://apache.cs.utah.edu/kafka/0.8.2.2/kafka_2.10-0.8.2.2.tgz"
# RUN tar -xzf zookeeper-3.4.10.tar.gz 
# RUN mv zookeeper-3.4.10 zookeeper 
# RUN mv zookeeper/conf/zoo_sample.cfg zookeeper/conf/zoo.cfg 
# EXPOSE 2181 2888 3888
# WORKDIR /zookeeper
# ENTRYPOINT ["/zookeeper/bin/zkServer.sh"]
# CMD ["start"]